accounts/urls.py
from django.urls import path
from accounts import views
from django.contrib.auth import views as auth_view

app_name = "accounts"

urlpatterns = [
    path("signup/", views.accounts_signup, name="signup"),
    path("logins/", auth_view.LoginView.as_view(template_name="accounts/login.html"), name="login"),
    path("logout/", auth_view.LogoutView.as_view(), name="logout"),
]

conf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", include("dista.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dista/urls.py
from django.urls import path
from dista import views


app_name = "dista"

urlpatterns = [
    path("add/", views.dista_add, name="dista_add"),
    path("update/<int:pk>", views.dista_update, name="dista_update"),
    path("delete/<int:pk>", views.dista_delete, name="dista_delete"),    
    path("detail/<int:pk>", views.dista_detail, name="dista_detail"),
    path("profile/<int:pk>", views.dista_profile, name="dista_profile"),
    path("likes/", views.dista_like, name="dista_like"),
    path("dis_likes/", views.dista_dis_like, name="dista_dis_like"),
    path("following/", views.dista_following, name="dista_following"),
    path("", views.dista_main, name="dista_main"),
]

base/models.py
from django.db import models
from datetime import datetime

class BaseModel(models.Model):
    created = models.DateTimeField(auto_now_add = True) 
    updated = models.DateTimeField(auto_now = True) 
    deleted = models.DateTimeField(null=True, blank=True)
    is_deleted = models.BooleanField(default=False, blank=True)


    class Meta:
        abstract = True


    def delete(self, using=None, Keep_parents=False):
        self.is_deleted = True
        self.deleted = datetime.now()
        self.save()

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>
    {% include 'navbar.html' %}
    {% block content %}

    {% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    
    {% block js %}
    
    {% endblock %}
</body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-white">
    <div class="container-fluid">
      {% load static %}
      <a class="navbar-brand" href="{% url 'dista:dista_main' %}"><img src="{% static 'img/로고.png' %}"></a>
      {% if user.is_authenticated %}  

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active btn btn-primary" aria-current="page" href="{% url 'dista:dista_add' %}">글쓰기</a>
          </li>
        </ul>
        
       

      </div>
          <a class="nav-link" href="{% url 'dista:dista_profile' request.user.pk %}">내 정보</a>
          <a class="nav-link btn btn-danger" href="{% url 'accounts:logout' %}">로그아웃</a>
        {% endif %}
    </div>
  </nav>
  <hr>