conf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", include("dista.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dista/urls.py
from django.urls import path
from dista import views


app_name = "dista"

urlpatterns = [
    path("add/", views.dista_add, name="dista_add"),
    path("update/<int:pk>", views.dista_update, name="dista_update"),
    path("delete/<int:pk>", views.dista_delete, name="dista_delete"),    
    path("detail/<int:pk>", views.dista_detail, name="dista_detail"),
    path("profile/<int:pk>", views.dista_profile, name="dista_profile"),
    path("likes/", views.dista_like, name="dista_like"),
    path("dis_likes/", views.dista_dis_like, name="dista_dis_like"),
    path("following/", views.dista_following, name="dista_following"),
    path("", views.dista_main, name="dista_main"),
]

dista/models.py
from django.db import models
from base.models import BaseModel
from django.conf import settings
from django.shortcuts import reverse


class Post(BaseModel):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="Photo/%Y-%m-%d")
    hash_tag = models.CharField(max_length=30, help_text="해쉬태그는 #를 따로 쓰지마세요 공백으로 자동구분 됩니다.")
    like = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="likes", blank=True) 
    dis_like = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="dis_likes", blank=True) 

    class Meta:
        ordering = ("-created", )
        db_table = "post"
        verbose_name = "작성된 포스트"
        verbose_name_plural = "모든 포스트"

    def __str__(self):
        return str(self.author)+"의 글"

    def get_absolute_url(self):
        return reverse("dista:dista_detail", args=[self.pk])

class Comment(BaseModel):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="posts")
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    comment = models.CharField(max_length=100)

    class Meta:
        ordering = ("-created", )
        db_table = "comment"
        verbose_name = "작성된 댓글"
        verbose_name_plural = "모든 댓글"

    def __str__(self):
        return str(self.author)+"님의 댓글"

dista/forms.py
from django import forms
from dista.models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ("image", "hash_tag")

    def clean_hash_tag(self):
        check = self.cleaned_data.get("hash_tag")
        check1 = ""
        for i in check:
            if i == "#":
                del(i)
            else:
                check1 += i
        print(check1)
        
        check = check1.replace(" ", " #")
        return "#"+check

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("comment", )

dista/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from dista.models import Post, Comment
from users.models import User
from dista.forms import PostForm, CommentForm
from django.http import HttpResponse
import json

@login_required
def dista_main(request):
    post_list = Post.objects.filter(is_deleted=False)
    return render(request, "dista/dista_main.html", {"post_list": post_list})


def dista_add(request):
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            data = form.save(commit=False) 
            data.author = request.user
            data.save()
            return redirect("dista:dista_main")
    else:
        form = PostForm()
    return render(request, "dista/dista_add.html", {"form": form})


def dista_update(request, pk):
    post = get_object_or_404(Post, id=pk)
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            data = form.save(commit=False)
            data.author = request.user
            data.save()
            return redirect("dista:dista_main")
    else:
        form = PostForm(instance=post)
    return render(request, "dista/dista_update.html", {"post": post, "form": form})


def dista_delete(request, pk):
    post = get_object_or_404(Post, id=pk)
    post.delete()
    return redirect("dista:dista_main")



def dista_detail(request, pk):
    post = get_object_or_404(Post, id=pk)
    comment_list = Comment.objects.filter(post=post, is_deleted=False)
    if request.method == "POST":
        data = Comment.objects.create(
            post=post,
            author=request.user,
            comment=request.POST.get("comment"))
        data.save()
    return render(request, "dista/dista_detail.html", {"post": post, "comment_list": comment_list})


def dista_profile(request, pk):
    user = get_object_or_404(User, id=pk)
    posts = Post.objects.filter(author=user, is_deleted=False)
    return render(request, "dista/dista_profile.html", {"user": user, "posts": posts})


def dista_like(request):
    if request.is_ajax():
        post_id = request.GET.get("post_id")
        post = Post.objects.get(id=post_id)
    if not request.user.is_authenticated:
        message = "로그인을 해주세욥"
        context = {"like_count": post.like.count(), "message": message}
        return HttpResponse(json.dumps(context), content_type="application/json")

    if request.user in post.like.all():
        post.like.remove(request.user)
        message = "좋아요를 취소합니다."
    else: 
        post.like.add(request.user)
        message = "좋아요를 눌렀습니다."
    context = {'like_count' : post.like.count(), "message":message}
    return HttpResponse(json.dumps(context), content_type="application/json")

def dista_dis_like(request):
    if request.is_ajax():
        post = Post.objects.get(id=request.GET.get("post_id"))
    
    if not request.user.is_authenticated:
        message = "로그인을 해주세요"
        context = {"dis_like_count": post.dis_like.count(), "message": message}
        return HttpResponse(json.dumps(context), content_type="application/json")

    if request.user in post.dis_like.all():
        post.dis_like.remove(request.user)
        message = "싫어요를 취소합니다."
    else:
        post.dis_like.add(request.user)
        message = "싫어요를 눌렀습니다."

    context = {"dis_like_count": post.dis_like.count(), "message": message}
    return HttpResponse(json.dumps(context), content_type="application/json")

def dista_following(request):
    pass
    if request.is_ajax():
        user = User.objects.get(id=request.GET.get("user_id"))

    if not request.user.is_authenticated:
        message = "로그인을 해주세요"
        context = {"following_count": user.following.count(), "message": message}
        return HttpResponse(json.dumps(context), content_type="application/json")

    if request.user == user:
        message = "자기 자신을 팔로잉 할순 없습니다"
        context = {"following_count": user.following.count(), "message": message}
        return HttpResponse(json.dumps(context), content_type="application/json")
    
    if request.user in user.following.all():
        user.following.remove(request.user)
        message = "팔로잉이 끊어졌어요"
    else:
        user.following.add(request.user)
        message = "팔로잉이 맺어졌어요"

    context = {"following_count": user.following.count(), "message": message}
    print(context)
    return HttpResponse(json.dumps(context), content_type="application/json")

dista/templates/dista/dista_add.html
{% extends 'base.html' %}

{% block title %}메인 페이지{% endblock %}
{% block content %}
<br><br>
<div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {% load bootstrap4 %}
            {% bootstrap_form form %}
            <input type="submit" value="글 등록">
        </form>
    </div>
    </div>
    <div class="col-md-4"></div>
</div>
{% endblock %}

dista/templates/dista/dista_detail.html
{% extends 'base.html' %}

{% block title %}메인 페이지{% endblock %}
{% block content %}
<br><br>
<div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-4" style="padding-bottom: 30px;">
        <div class="card">
            <div class="card-body badge badge-secondary">
                {{ post.author }}님  {{ post.created | timesince }}, 전 작성
            </div>
            <div class="card-body">
                <img src="{{ post.image.url }}" width="100%"><hr>
                <p style="color: blue";>{{ post.hash_tag }}</p>

                {% load static %}
                <a href="{% url 'dista:dista_profile' post.author.id %}"><img src="{% static 'img/프로필.png' %}"></a>
                <button id="{{ post.id }}" onclick="click_like(this.id)" class="btn btn-white">
                    <img src="{% static 'img/좋아요.png' %}">
                    <span id="like_count">{{post.like.all|length}}</span>
                </button>
                <button id="{{ post.id }}" onclick="click_dis_like(this.id)" class="btn btn-white">
                    <img src="{% static 'img/싫어요.png' %}">
                    <span id="dis_like_count">{{ post.dis_like.all|length}}</span>
                </button>
                <br><h7 class="badge badge-secondary" id="message"></h7>
                <hr>
                {% if post.author == request.user %}
                    <a href="{% url 'dista:dista_update' post.pk  %}" style="color: green;">수정</a>
                    <a href="{% url 'dista:dista_delete' post.pk  %}" style="color: red;">삭제</a>
                    <br>
                {% endif %}
                댓글 ({{post.posts.all|length}})
            </div>
        </div>
    </div>
    <div class="col-md-5">
        <p class="alert alert-success text-center">댓글 남기기</p>
        {% for comment in comment_list %}
        <div class="form-group mt-1">
            <small class="badge badge-info">{{ comment.comment }}</small><br>
            <small><strong>작성자 : {{ comment.author.nick_name }}</strong></small>
            <small>({{comment.created|timesince}}), 전 작성됨</small>
        </div>
        {% endfor %}

        <div class="form-group">    
            <form action="" method="POST">
                {% csrf_token %}
                    <textarea name="comment" class="form-control" rows="2" placeholder="댓글을 입력해주세요"></textarea>
                    <input class="btn btn-primary mt-2" type="submit" value="댓글 등록">
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block js %}
<script>
    function click_like(post_id) {
        $.ajax({
            url: "{% url 'dista:dista_like' %}",
            data: {
                "post_id": post_id
            },
            dataType: "json",
            success: function (response) {
                $('#like_count').html(response.like_count)
                $('#message').html(response.message)
            }
        })
    }
</script>

<script>
    function click_dis_like(post_id) {
        $.ajax({
            url: "{% url 'dista:dista_dis_like' %}",
            data: {
                "post_id": post_id
            },
            dataType: "json",
            success: function (response) {
                $("#dis_like_count").html(response.dis_like_count)
                $("#message").html(response.message)
            }
        })
    }


</script>

{% endblock %}

dista/templates/dista/dista_main.html
{% extends 'base.html' %}

{% block title %}메인 페이지{% endblock %}
{% block content %}
<br><br>
<div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4" style="padding-bottom: 50px;">
        {% for post in post_list %} <br>
        <div class="card">
            <div class="card-body badge badge-secondary" >
                {{ post.author }}님  {{ post.created | timesince }}, 전 작성
            </div>
            <div class="card-body">
                <a href="{{ post.get_absolute_url }}"><img src="{{ post.image.url }}" width="100%"></a><hr>
                <p style="color: blue";>{{ post.hash_tag }}</p>

                {% load static %}
                <a href="{% url 'dista:dista_profile' post.author.id %}"><img src="{% static 'img/프로필.png' %}"></a>
                    <img src="{% static 'img/좋아요.png' %}"> {{ post.like.all|length }}
                    <img src="{% static 'img/싫어요.png' %}"> {{ post.dis_like.all|length}}
                <hr>
                {% if post.author == request.user %}
                    <a href="{% url 'dista:dista_update' post.pk  %}" style="color: green;">수정</a>
                    <a href="{% url 'dista:dista_delete' post.pk  %}" style="color: red;">삭제</a>
                    <br>
                {% endif %}

                댓글 ({{post.posts.all|length}}) <a href="{% url 'dista:dista_detail' post.pk %}">댓글쓰기</a>
                <hr>
                
            </div>
        </div>
        {% endfor %} 
    </div>
    </div>
    <div class="col-md-4"></div>
</div>
{% endblock %}

dista/templates/dista/dista_profile.html
{% extends 'base.html' %}

{% block title %}메인 페이지{% endblock %}
{% block content %}
<br><br>
<div class="row">
    <div class="col-md-3">
        <div class="card">
            <div class="card-body text-center">
                닉네임 : {{ user.nick_name }} <br>
                아이디 : {{ user.username }} <br>
                팔로워 : <h7 id="following_count">{{ user.following.all|length }}</h7>명<br>
                <hr>
                {% if user.nick_name != request.user.nick_name %}
                <button id="{{ user.id }}" onclick="following_click(this.id)" class="btn btn-info">팔로잉</button>
                {% endif %} <br>
                <h7 id="message"></h7>
            </div>
        </div>
    </div>
    <div class="col-md-5">
        <p class="alert alert-success text-center">{{ user.nick_name }} 님이 작성한 글 목록 입니다.</p>
        {% for post in posts %}
        <div class="card">
            <div class="card-body">
                    {% load static %}
                    <a href="{{ post.get_absolute_url }}">{{ post.hash_tag }}</a>
                    <img src="{% static 'img/좋아요.png' %}"> {{ post.like.all|length}}
                    <img src="{% static 'img/싫어요.png' %}"> {{ post.dis_like.all|length}}
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="col-md-4">
        
    </div>
</div>
{% endblock %}

{% block js %}
<script>
    function following_click(user_id) {
        $.ajax({
            url: "{% url 'dista:dista_following' %}",
            data: {
                "user_id": user_id
            },
            dataType: "json",
            success: function (response) {
                $('#following_count').html(response.following_count)
                $('#message').html(response.message)
            }
        })
    }
</script>
{% endblock %}

dista/templates/dista/dista_update.html
{% extends 'base.html' %}

{% block title %}메인 페이지{% endblock %}
{% block content %}
<br><br>
<div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">
        <p class="alert alert-danger">최근 업데이트 일시 : {{ post.updated|timesince }}, 전</p>
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {% load bootstrap4 %}
            {% bootstrap_form form %}
            <input type="submit" value="글 등록">
        </form>
    </div>
    </div>
    <div class="col-md-4"></div>
</div>
{% endblock %}